[package]
name = "risc0-guest"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
risc0-zkvm = { version = "^2.3.0", default-features = false, features = [
    'std',
] }

# Ream dependencies
ream-consensus = { workspace = true }
