[package]
name = "methods"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[build-dependencies]
risc0-build = { version = "^2.3.0" }

[dependencies]
# Ream dependencies
ream-consensus = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]
